import { TableOptions } from "@/components/tables/tableOptions.types";
import NewTable from "@/components/tables/Table";
import React from "react";

const tableOptions: TableOptions = {
  uniqueKey: "id",
  search: true,
  select: true,
  filter: {
    active: false,
    filterBy: [],
  },
  saveData: true,
  pagination: true,
  sort: true,
  settings: {
    title: "usersTable",
    active: true,
  },
  create: {
    active: true,
    link: "",
  },
  actions: {
    active: true,
    actions: [
      {
        key: "id",
        name: "change",
        type: "LINK",
        link: "wasdxasdsad",
      },
    ],
  },
};

const NewTableTest = () => {
  const data = [
    {
      id: 20,
      city: null,
      email: "dsfsdfds@gmail.com",
      address: null,
      country: "ca",
      balance: 0,
      birthday: null,
      last_name: "dfsdfsdf",
      user_name: "asdsadsad",
      first_name: "gdfsdfsdf",
      is_verified: 0,
      is_activated: true,
      mobile_number: null,
      email_verified_at: null,
      created_at: "2024-10-20 15:42:29",
      updated_at: "2024-10-20 15:42:29",
      roles: [],
    },
    {
      id: 19,
      city: null,
      email: "gioocharkviani@gmail.com",
      address: null,
      country: "ca",
      balance: 0,
      birthday: null,
      last_name: "charkviani",
      user_name: "gioocharkviani3",
      first_name: "giorgi",
      is_verified: 0,
      is_activated: true,
      mobile_number: null,
      email_verified_at: null,
      created_at: "2024-10-09 08:00:52",
      updated_at: "2024-10-09 08:00:52",
      roles: ["ADMIN"],
    },
    {
      id: 18,
      city: null,
      email: "giogio@gmail.com",
      address: null,
      country: "ca",
      balance: 0,
      birthday: null,
      last_name: "charkviani",
      user_name: "gioocharkviani2",
      first_name: "giorgi",
      is_verified: 0,
      is_activated: true,
      mobile_number: null,
      email_verified_at: null,
      created_at: "2024-10-09 08:00:01",
      updated_at: "2024-10-09 08:00:01",
      roles: [],
    },
    {
      id: 17,
      city: null,
      email: "a@a1.com",
      address: null,
      country: "Georgia",
      balance: 0,
      birthday: null,
      last_name: "cadsd",
      user_name: "gioocharkviani1",
      first_name: "gio",
      is_verified: 0,
      is_activated: true,
      mobile_number: null,
      email_verified_at: null,
      created_at: "2024-10-05 10:34:19",
      updated_at: "2024-10-05 10:34:19",
      roles: [],
    },
    {
      id: 16,
      city: null,
      email: "aiia@gmail.com",
      address: null,
      country: "Georgia",
      balance: 0,
      birthday: null,
      last_name: "gogebashvili",
      user_name: "aiia",
      first_name: "iakob",
      is_verified: 0,
      is_activated: true,
      mobile_number: null,
      email_verified_at: null,
      created_at: "2024-10-03 10:28:04",
      updated_at: "2024-10-03 10:28:04",
      roles: [],
    },
    {
      id: 15,
      city: null,
      email: "1a@a.com",
      address: null,
      country: "Georgia",
      balance: 0,
      birthday: null,
      last_name: "charkviani",
      user_name: "gioocharkviani",
      first_name: "giorgi",
      is_verified: 0,
      is_activated: true,
      mobile_number: null,
      email_verified_at: null,
      created_at: "2024-10-03 07:57:21",
      updated_at: "2024-10-03 07:57:21",
      roles: ["SUPER_ADMIN"],
    },
    {
      id: 14,
      city: null,
      email: "a@a.com",
      address: null,
      country: "Georgia",
      balance: 0,
      birthday: null,
      last_name: "Gonjilashvili",
      user_name: "gonjila",
      first_name: "Lasha",
      is_verified: 0,
      is_activated: true,
      mobile_number: null,
      email_verified_at: null,
      created_at: "2024-10-02 23:37:39",
      updated_at: "2024-10-02 23:37:39",
      roles: ["SUPER_ADMIN"],
    },
    {
      id: 1,
      city: null,
      email: "schaefer.jordyn@example.net",
      address: null,
      country: "Cote d'Ivoire",
      balance: 0,
      birthday: "1986-03-04 05:58:17",
      last_name: "Vandervort",
      user_name: "Karianne O'Connell",
      first_name: "Pedro",
      is_verified: 0,
      is_activated: true,
      mobile_number: null,
      email_verified_at: "2024-10-01T19:05:43.000000Z",
      created_at: "2024-10-01 19:05:43",
      updated_at: "2024-10-01 19:05:43",
      roles: [],
    },
    {
      id: 2,
      city: null,
      email: "kaden.smith@example.org",
      address: null,
      country: "Isle of Man",
      balance: 0,
      birthday: "1982-11-08 14:04:58",
      last_name: "Jast",
      user_name: "Ulices Carroll DDS",
      first_name: "Zachary",
      is_verified: 0,
      is_activated: true,
      mobile_number: null,
      email_verified_at: "2024-10-01T19:05:43.000000Z",
      created_at: "2024-10-01 19:05:43",
      updated_at: "2024-10-01 19:05:43",
      roles: [],
    },
    {
      id: 3,
      city: null,
      email: "elza50@example.org",
      address: null,
      country: "Madagascar",
      balance: 0,
      birthday: "1994-12-15 01:14:49",
      last_name: "Zieme",
      user_name: "Bailey Will V",
      first_name: "Michele",
      is_verified: 0,
      is_activated: true,
      mobile_number: null,
      email_verified_at: "2024-10-01T19:05:43.000000Z",
      created_at: "2024-10-01 19:05:43",
      updated_at: "2024-10-01 19:05:43",
      roles: [],
    },
  ];
  return <NewTable data={data} options={tableOptions} />;
};

export default NewTableTest;
